In [2]:
import pandas as pd
data={"Name":["parth","Dev","Sourav","Prathmesh","Nishant"],
      "Graduation Percentage":[89,90,99,78,77],
      "Age":[20,21,22,19,21]}

df=pd.DataFrame(data)
print(df)
print("Average age",df["Age"].mean())
print("Graduation Percentage: ",df["Graduation Percentage"].mean())

print("Median=",df["Graduation Percentage"].median())
print("Median=",df["Age"].median())

print("Mode=",df["Graduation Percentage"].mode())
print("Mode=",df["Age"].mode())

print("Range=",df["Graduation Percentage"].max()-df["Graduation Percentage"].min())
print("Range=",df["Age"].max()-df["Age"].min())

print("Quartile=",df["Graduation Percentage"].quantile(0.25))
print("Quartile=",df["Age"].quantile([0.25,0.50,0.75]))

print("Variance=",df["Graduation Percentage"].var())
print("Variance=",df["Age"].var())

        Name  Graduation Percentage  Age
0      parth                     89   20
1        Dev                     90   21
2     Sourav                     99   22
3  Prathmesh                     78   19
4    Nishant                     77   21
Average age 20.6
Graduation Percentage:  86.6
Median= 89.0
Median= 21.0
Mode= 0    77
1    78
2    89
3    90
4    99
Name: Graduation Percentage, dtype: int64
Mode= 0    21
Name: Age, dtype: int64
Range= 22
Range= 3
Quartile= 78.0
Quartile= 0.25    20.0
0.50    21.0
0.75    21.0
Name: Age, dtype: float64
Variance= 84.30000000000001
Variance= 1.3

In [3]:
print(df.describe())

       Graduation Percentage        Age
count               5.000000   5.000000
mean               86.600000  20.600000
std                 9.181503   1.140175
min                77.000000  19.000000
25%                78.000000  20.000000
50%                89.000000  21.000000
75%                90.000000  21.000000
max                99.000000  22.000000

In [4]:
df

        Name  Graduation Percentage  Age
0      parth                     89   20
1        Dev                     90   21
2     Sourav                     99   22
3  Prathmesh                     78   19
4    Nishant                     77   21

In [5]:
df.head(2)

    Name  Graduation Percentage  Age
0  parth                     89   20
1    Dev                     90   21

In [6]:
df.tail(3)

        Name  Graduation Percentage  Age
2     Sourav                     99   22
3  Prathmesh                     78   19
4    Nishant                     77   21