# Download the heights and weights dataset and load the dataset from a given csv file into a dataframe. Print the first, last 10 rows and random 20 rows

In [1]:
import pandas as pd
data=pd.read_csv("HeightWeight.csv")
data

       Index  Height(Inches)  Weight(Pounds)
0          1        65.78331        112.9925
1          2        71.51521        136.4873
2          3        69.39874        153.0269
3          4        68.21660        142.3354
4          5        67.78781        144.2971
...      ...             ...             ...
24995  24996        69.50215        118.0312
24996  24997        64.54826        120.1932
24997  24998        64.69855        118.2655
24998  24999        67.52918        132.2682
24999  25000        68.87761        124.8742

[25000 rows x 3 columns]

In [2]:
print("For First 10 rows:\n",data.head(10))

For First 10 rows:
    Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971
5      6        68.69784        123.3024
6      7        69.80204        141.4947
7      8        70.01472        136.4623
8      9        67.90265        112.3723
9     10        66.78236        120.6672

In [3]:
print("For Last 10 rows:\n",data.tail(10))

For Last 10 rows:
        Index  Height(Inches)  Weight(Pounds)
24990  24991        69.97767        125.3672
24991  24992        71.91656        128.2840
24992  24993        70.96218        146.1936
24993  24994        66.19462        118.7974
24994  24995        67.21126        127.6603
24995  24996        69.50215        118.0312
24996  24997        64.54826        120.1932
24997  24998        64.69855        118.2655
24998  24999        67.52918        132.2682
24999  25000        68.87761        124.8742

In [4]:
print("For random 20 rows:\n",data.sample(20))     # sample() is used to print random number of rows

For random 20 rows:
        Index  Height(Inches)  Weight(Pounds)
3208    3209        69.03818        143.4850
4608    4609        70.16738        131.5040
23914  23915        66.32387        126.5144
21307  21308        67.35410        126.4415
6181    6182        67.95175        128.2412
5796    5797        66.69106        132.6528
13439  13440        66.21090        125.9366
4122    4123        67.60704        127.5160
20336  20337        66.81235        134.9879
24393  24394        64.98386        100.1129
2108    2109        67.59652        120.2168
3932    3933        65.97406        120.1281
18696  18697        67.87278        147.5407
16111  16112        69.15274        125.9758
1798    1799        66.63059        133.5937
11452  11453        68.24513        128.9407
15196  15197        68.22649        135.6941
8993    8994        63.79579        113.0481
17994  17995        70.31771        126.9513
11182  11183        67.22009        133.8821

# Write a Python program to find the shape,size,datatypes of the dataframe object

In [9]:
print(f"Information about Given datasets:\n\nShape: {data.shape}\n\nSize:{data.size}\n\nDatatypes:{data.dtypes}\n\nInfo:\n{data.info()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Index           25000 non-null  int64
 1   Height(Inches)  25000 non-null  float64
 2   Weight(Pounds)  25000 non-null  float64
 3   BMI             25000 non-null  float64
dtypes: float64(3), int64(1)
memory usage: 781.4 KB
Information about Given datasets:

Shape: 25000

Size:100000

Datatypes:Index               int64
Height(Inches)    float64
Weight(Pounds)    float64
BMI               float64
dtype: object

Info:
None

# Write a python program to view basic statistical details of the data

In [6]:
print(f"Basics Statistical details of the given dataset:\n{data.describe()}")

Basics Statistical details of the given dataset:
              Index  Height(Inches)  Weight(Pounds)
count  25000.000000    25000.000000    25000.000000
mean   12500.500000       67.993114      127.079421
std     7217.022701        1.901679       11.660898
min        1.000000       60.278360       78.014760
25%     6250.750000       66.704397      119.308675
50%    12500.500000       67.995700      127.157750
75%    18750.250000       69.272958      134.892850
max    25000.000000       75.152800      170.924000

# Write a python program to get the number of observations,missing values and nan values

In [7]:
print(f"No of Observations:{data.shape}\nMissing values in each columns:{data.isnull().sum()}\n\nTotal missing values in the entire dataset:{data.isnull().sum().sum()}\n")
print(f"Nan values in each columns:{data.isna().sum()}\n\nTotal Nan values in the entire dataset:{data.isna().sum().sum()}")

No of Observations:(25000, 3)
Missing values in each columns:Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

Total missing values in the entire dataset:0

Nan values in each columns:Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

Total Nan values in the entire dataset:0

# Write a python program to add a columns to the dataframe "BMI" which is calculated as:weight/height2

In [27]:
data["BMI"] = data["Weight(Pounds)"] * 703  / (data["Height(Inches)"]**2)

# Display updated DataFrame
print(data)

       Index  Height(Inches)  Weight(Pounds)        BMI
0          1        65.78331        112.9925  18.355808
1          2        71.51521        136.4873  18.760773
2          3        69.39874        153.0269  22.336747
3          4        68.21660        142.3354  21.502458
4          5        67.78781        144.2971  22.075458
...      ...             ...             ...        ...
24995  24996        69.50215        118.0312  17.177330
24996  24997        64.54826        120.1932  20.279916
24997  24998        64.69855        118.2655  19.862061
24998  24999        67.52918        132.2682  20.390497
24999  25000        68.87761        124.8742  18.504268

[25000 rows x 4 columns]

In [26]:
data=data.drop("BMI",axis=1)
data

       Index  Height(Inches)  Weight(Pounds)
0          1        65.78331        112.9925
1          2        71.51521        136.4873
2          3        69.39874        153.0269
3          4        68.21660        142.3354
4          5        67.78781        144.2971
...      ...             ...             ...
24995  24996        69.50215        118.0312
24996  24997        64.54826        120.1932
24997  24998        64.69855        118.2655
24998  24999        67.52918        132.2682
24999  25000        68.87761        124.8742

[25000 rows x 3 columns]